#!/usr/bin/env python3
"""Generate the shared father-son training doc (father_son_training.md).

Reads Papá's plan (plan_papa.json) and Emmanuel's LIVE plan (Postgres, default)
and renders a single side-by-side view of the shared Saturday long runs, so both
know what each weekend's long run is and where they converge. Regenerate anytime
either plan changes.

Alignment: both race Oct 2. Papá week N (starts Jul 13) shares the calendar with
Emmanuel week N+19.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

RUNNING_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(RUNNING_DIR))

PAPA_OFFSET = 19  # Papá week N  <->  Emmanuel week N+19 (same calendar weekend)


def main() -> int:
    from dotenv import load_dotenv
    load_dotenv()
    from tracker import db
    db.init_db()

    papa = json.loads((RUNNING_DIR / "plan_papa.json").read_text())
    emm_plan = {w["week_number"]: w for w in db.get_plan()}  # default = Emmanuel

    lines = [
        "# Father & Son — Ultra Trail Tarahumara 59 km (Oct 2, 2026)",
        "",
        "Shared training plan. **Every long run is Saturday, same trail.** Papá is fitter "
        "with a bigger base, so he runs longer — Emmanuel runs the common distance and Papá "
        "continues for his extra. The gap closes through the build.",
        "",
        "| Weekend | Emmanuel long | Papá long | Together |",
        "|---------|--------------|-----------|----------|",
    ]
    catch_week = None
    for w in papa["weeks"]:
        n = w["week_number"]
        dates = f"{w['start_date'][5:]}–{w['end_date'][5:]}"
        papa_long = w["long_run_km"]
        if n == 12:  # race week
            lines.append(f"| **{dates}** | **RACE** | **RACE** | 🏔️ **59 km side by side** |")
            continue
        emm = emm_plan.get(n + PAPA_OFFSET)
        emm_long = emm["long_run_km"] if emm else None
        emm_rec = emm["is_recovery"] if emm else False
        if emm_long is None:
            note = "run together"
        elif w["is_recovery"] and emm_rec:
            note = "both easy — recovery"
        elif emm_long >= papa_long:
            note = f"🎯 **you MATCH/PASS him** ({emm_long:.0f} vs {papa_long:.0f})"
            catch_week = dates
        else:
            note = f"together, he continues +{papa_long - emm_long:.0f}"
        el = f"{emm_long:.0f}" if emm_long is not None else "—"
        lines.append(f"| {dates} | {el} | {papa_long:.0f} | {note} |")

    lines += [
        "",
        "## The catch-up",
        "",
        f"Emmanuel is coming back from injury, so his long runs start shorter and build. "
        f"**The gap closes to zero the weekend of {catch_week or 'his peak'}** — his peak long "
        "run pulls level with (and edges past) Papá's on their shared Saturday. After that Papá "
        "does one solo peak while Emmanuel tapers, and on **Oct 2 they run the 59 km together.**",
        "",
        "## How to run it together",
        "",
        "- **Saturday = the shared long run.** Meet at the same trailhead, run the common "
        "distance together; whoever's going longer continues, whoever's easing turns back.",
        "- **Recovery weekends** (both marked *recovery*): keep it genuinely easy — that's the point.",
        "- **Peak long runs:** Papá ~37 km, Emmanuel ~34 km — run-hike, fuel every 40–45 min, "
        "protect the quads on the descents.",
        "- The rest of the week each follows their own plan (`plan_papa.md` / the coach).",
        "",
        "_Generated by `scripts/father_son_plan.py` from both live plans._",
    ]

    out = RUNNING_DIR / "father_son_training.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"Wrote {out} ({len(papa['weeks'])} weeks; catch-up weekend: {catch_week})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
