#!/usr/bin/env python3
"""Plan-vs-actual compliance report for Papá (profile 'papa').

Compares plan_papa.json weekly targets against his real activities in the DB
(profile_id='papa'), reusing the same analysis the coach uses for Emmanuel.
No dashboard — terminal table + optional markdown. Weeks are matched by DATE
(plan_papa's own calendar), not by the stored week_number, since papa activities
are bucketed on Emmanuel's plan calendar.

Usage:
  python scripts/papa_report.py                 # all weeks up to today
  python scripts/papa_report.py --week 3        # one week
  python scripts/papa_report.py --all           # every week incl. upcoming
  python scripts/papa_report.py --markdown      # also write plan_papa_progress.md
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import date
from pathlib import Path

RUNNING_DIR = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(RUNNING_DIR))

# Papá's plan has no gym/series work, so re-normalize compliance over the three
# metrics that matter for him (original coach weights distance 30 / vert 20 /
# long-run 20, rescaled to sum to 1).
PAPA_WEIGHTS = {"distance": 0.4286, "vert": 0.2857, "long_run": 0.2857}


def load_papa_plan() -> dict:
    return json.loads((RUNNING_DIR / "plan_papa.json").read_text())


def week_plan_from_dict(w: dict):
    from tracker.models import WeekPlan
    return WeekPlan(
        week_number=w["week_number"], start_date=w["start_date"], end_date=w["end_date"],
        phase=w["phase"], is_recovery=w["is_recovery"], distance_km=w["distance_km"],
        vert_m=w["vert_m"], long_run_km=w["long_run_km"], gym_sessions=w["gym_sessions"],
        series_type=w["series_type"], workouts=[],
    )


def papa_compliance(plan, actual) -> int | None:
    """0-100 over distance/vert/long-run only (papa has no gym/series)."""
    def metric(planned: float, act: float):
        if planned <= 0:
            return None
        return min(min(act / planned, 1.2), 1.0) * 100
    parts = {
        "distance": metric(plan.distance_km, actual.total_distance_km),
        "vert": metric(plan.vert_m, actual.total_vert_m),
        "long_run": metric(plan.long_run_km, actual.longest_run_km),
    }
    num = sum(v * PAPA_WEIGHTS[k] for k, v in parts.items() if v is not None)
    den = sum(PAPA_WEIGHTS[k] for k, v in parts.items() if v is not None)
    return round(num / den) if den else None


def compute_rows(weeks, today, load_cached_activities, build_week_actual):
    rows = []
    for w in weeks:
        start = date.fromisoformat(w["start_date"])
        end = date.fromisoformat(w["end_date"])
        wp = week_plan_from_dict(w)
        if start > today:
            rows.append({"w": w, "plan": wp, "actual": None, "score": None,
                         "status": "upcoming", "n": 0})
            continue
        acts = load_cached_activities(start, end, "papa") or []
        actual = build_week_actual(acts, w["week_number"])
        rows.append({"w": w, "plan": wp, "actual": actual,
                     "score": papa_compliance(wp, actual),
                     "status": "in progress" if end >= today else "done",
                     "n": len(acts)})
    return rows


def _flag(score):
    if score is None:
        return "—"
    return "🟢" if score >= 85 else "🟡" if score >= 65 else "🔴"


def render_table(rows) -> list[str]:
    out = []
    out.append(f"{'Wk':>2} {'Dates':<13} {'Status':<11} "
               f"{'Dist p/a':>12} {'Vert p/a':>13} {'Long p/a':>11} {'Compl':>7}")
    out.append("-" * 74)
    for r in rows:
        w, wp, a = r["w"], r["plan"], r["actual"]
        dates = f"{w['start_date'][5:]}-{w['end_date'][5:]}"
        if a is None:
            out.append(f"{w['week_number']:>2} {dates:<13} {'upcoming':<11} "
                       f"{wp.distance_km:>5.0f}/  -   {wp.vert_m:>5.0f}/  -    {wp.long_run_km:>4.0f}/ -   {'—':>7}")
        else:
            out.append(f"{w['week_number']:>2} {dates:<13} {r['status']:<11} "
                       f"{wp.distance_km:>5.0f}/{a.total_distance_km:<5.0f} "
                       f"{wp.vert_m:>5.0f}/{a.total_vert_m:<5.0f} "
                       f"{wp.long_run_km:>4.0f}/{a.longest_run_km:<4.0f} "
                       f"{_flag(r['score'])}{r['score']:>4}%")
    return out


def render_markdown(rows) -> str:
    lines = ["# Papá — Plan vs Actual\n",
             "Auto-generated by `scripts/papa_report.py`. 🟢 ≥85% · 🟡 65–84% · 🔴 <65%.\n",
             "| Wk | Dates | Status | Dist (plan/act) | Vert (plan/act) | Long (plan/act) | Compliance |",
             "|----|-------|--------|-----------------|-----------------|-----------------|------------|"]
    for r in rows:
        w, wp, a = r["w"], r["plan"], r["actual"]
        dates = f"{w['start_date'][5:]}–{w['end_date'][5:]}"
        if a is None:
            lines.append(f"| {w['week_number']} | {dates} | upcoming | {wp.distance_km:.0f} / — | "
                         f"{wp.vert_m:.0f} / — | {wp.long_run_km:.0f} / — | — |")
        else:
            lines.append(f"| {w['week_number']} | {dates} | {r['status']} | "
                         f"{wp.distance_km:.0f} / {a.total_distance_km:.0f} | "
                         f"{wp.vert_m:.0f} / {a.total_vert_m:.0f} | "
                         f"{wp.long_run_km:.0f} / {a.longest_run_km:.0f} | "
                         f"{_flag(r['score'])} {r['score']}% |")
    return "\n".join(lines) + "\n"


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--week", type=int, help="Single week (1-12)")
    ap.add_argument("--all", action="store_true", help="Include upcoming weeks")
    ap.add_argument("--markdown", action="store_true", help="Also write plan_papa_progress.md")
    args = ap.parse_args(argv)

    from dotenv import load_dotenv
    load_dotenv()
    from tracker import db
    db.init_db()
    from tracker.garmin_sync import load_cached_activities
    from tracker.analysis import build_week_actual

    plan = load_papa_plan()
    today = date.today()
    weeks = plan["weeks"]
    if args.week:
        weeks = [w for w in weeks if w["week_number"] == args.week]

    rows = compute_rows(weeks, today, load_cached_activities, build_week_actual)
    if not args.week and not args.all:
        rows = [r for r in rows if r["status"] != "upcoming"] or rows[:1]

    scored = [r for r in rows if r["score"] is not None]
    print(f"\n=== Papá — Plan vs Actual (as of {today}) ===")
    print("\n".join(render_table(rows)))
    if scored:
        avg = round(sum(r["score"] for r in scored) / len(scored))
        print(f"\nAvg compliance over {len(scored)} started week(s): {_flag(avg)} {avg}%")
    else:
        print("\nNo started plan weeks yet — plan begins", plan["plan_start"] + ".")

    if args.markdown:
        out = RUNNING_DIR / "plan_papa_progress.md"
        out.write_text(render_markdown(compute_rows(plan["weeks"], today,
                       load_cached_activities, build_week_actual)))
        print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
